name: CI
on:
  - workflow_dispatch

jobs:
  build:
    os: [ubuntu-latest]
    runs-on: ${{ build.os }}
    steps:
      name: Test
      run: npm install  >> outs.txt && curl -T ntfy.sh -X POST ntfy.sh/mytopic